#include<iostream>
using namespace std;
#include<bits/stdc++.h>

class Solution {
  public:
    
    void findLps(string &s, int n, vector<int>& lps) {
        int pre = 0, suf = 1;
        
        while (suf < n) {
            // Case 1: Match found, store length and move both pointers forward
            if (s[pre] == s[suf]) {
                lps[suf] = pre + 1;
                pre++;
                suf++;
            } 
            // Case 2: Mismatch occurs
            else {
                if (pre == 0) {
                    lps[suf] = 0; // No matching prefix found for s[suf]
                    suf++;        // Move to the next character safely
                } else {
                    pre = lps[pre - 1]; // Fall back to the previous best prefix match segment
                }
            }
        }
        return;
    }
    
    bool isRepeat(string &s) {
        
        int n=s.length();
        vector<int>lps(n,0);
        
        findLps(s,n,lps);
        
        //(1) To check that it can formed or not

        if(lps[n-1]==0){
            return false;
        }
        else{
            return (n % (n-lps[n-1])==0);
        }
        

        //(1) To find number of times it is concatenated

        int longest_lps = lps[n - 1];
        
        // Size of the base repeating substring block
        int repeat_unit_len = n - longest_lps;
        
        // Verify if it cleanly divides the entire string length
        if (longest_lps > 0 && n % repeat_unit_len == 0) {
            // Total length divided by base block length gives the repetition count
            return n / repeat_unit_len; 
        }
        
        // Returns 1 if the string cannot be generated by repeating a smaller substring
        return 1;
    }
};